In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

In [7]:
%pip install chardet

Collecting chardet
  Downloading chardet-5.2.0-py3-none-any.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.4/199.4 KB 3.5 MB/s eta 0:00:00a 0:00:01
Installing collected packages: chardet
Successfully installed chardet-5.2.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Note: you may need to restart the kernel to use updated packages.

In [8]:
import chardet

with open('05.csv', 'rb') as f:
    result = chardet.detect(fa.read())

data = pd.read_csv('05.csv', encoding=result['encoding'])

NameError: name 'fa' is not defined

In [9]:
import chardet

with open('05.csv', 'rb') as f:
    result = chardet.detect(f.read())

data = pd.read_csv('05.csv', encoding=result['encoding'])

In [11]:
data = pd.read_csv('05.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

In [17]:
data = pd.read_csv('05.csv', encoding='shift-jis')

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ïvNx        10 non-null     int64
 1   gDcÌº°ÄÞ    10 non-null     int64
 2   gDcÌªÌ¼  10 non-null     object
 3   ïvæª        10 non-null     int64
 4   ïvæª¼      10 non-null     object
 5   ûxæª        10 non-null     int64
 6   ÈÚº°ÄÞ        10 non-null     int64
 7   ÈÚ¼          10 non-null     object
 8   \Zz          10 non-null     object
 9    4ª          10 non-null     int64
 10   5ª          10 non-null     object
 11   6ª          10 non-null     object
 12   7ª          10 non-null     object
 13   8ª          10 non-null     object
 14   9ª          10 non-null     object
 15  10ª          10 non-null     object
 16  11ª          10 non-null     object
 17  12ª          10 non-null     int64
 18   1ª          10 non-null     int64
 19   2ª          10 non-null     int64
 20   3ª          10 non-null     int64
 21   4ª.1        10 non-null     int64
 22   5ª.1        10 non-null     int64
 23  Ýv            10 non-null     object
 24  ·s¦          10 non-null     object
dtypes: int64(12), object(13)
memory usage: 2.1+ KB

In [21]:
data.head(10)

,会計年度,組織団体ｺｰﾄﾞ,組織団体略称名,会計区分,会計区分名,収支区分,科目ｺｰﾄﾞ,科目名,予算額,4月分,...,10月分,11月分,12月分,1月分,2月分,3月分,4月分.1,5月分.1,累計,執行率
0,2023,11000000,会議所クラブ,1,須賀川会議所クラブ,2,1000000,会費,"1,065,000",0,...,"4,000",0,0,0,0,0,0,0,"1,004,000",94%
1,2023,11000000,会議所クラブ,1,須賀川会議所クラブ,2,2000000,登録料,"1,300,000",0,...,"116,000",0,0,0,0,0,0,0,"428,000",33%
2,2023,11000000,会議所クラブ,1,須賀川会議所クラブ,2,3000000,雑収入,"55,275",0,...,"6,000",0,0,0,0,0,0,0,"24,002",43%
3,2023,11000000,会議所クラブ,1,須賀川会議所クラブ,2,4000000,繰越金,"379,725",0,...,0,0,0,0,0,0,0,0,0,0%
4,2023,11000000,会議所クラブ,1,須賀川会議所クラブ,3,1000000,例会費,"1,200,000",0,...,0,"316,122",0,0,0,0,0,0,"514,824",43%
5,2023,11000000,会議所クラブ,1,須賀川会議所クラブ,3,2000000,会議費,"850,000",0,...,"79,618",0,0,0,0,0,0,0,"445,837",52%
6,2023,11000000,会議所クラブ,1,須賀川会議所クラブ,3,3000000,通信費,"100,000",0,...,"5,796",0,0,0,0,0,0,0,"26,639",27%
7,2023,11000000,会議所クラブ,1,須賀川会議所クラブ,3,4000000,委託費,"350,000",0,...,0,0,0,0,0,0,0,0,"350,000",100%
8,2023,11000000,会議所クラブ,1,須賀川会議所クラブ,3,5000000,雑費,"100,000",0,...,"7,000","1,430",0,0,0,0,0,0,"8,980",9%
9,2023,11000000,会議所クラブ,1,須賀川会議所クラブ,3,6000000,事業費,"200,000",0,...,0,0,0,0,0,0,0,0,0,0%

In [20]:
data.shape

(10, 25)